### ISSUE TITLE
Code: Resolve Security Identifier detection for Windows on ARM

### ISSUE THREAD

**Issue by khronokernel** [Nekrosis-ISS-Capstone/Nekrosis#5]
```
Traceback (most recent call last):
  File "nekrosis_entry.py", line 8, in <module>
  File "nekrosis\core.py", line 240, in main
    nekrosis = Nekrosis(
               ^^^^^^^^^
  File "nekrosis\core.py", line 57, in __init__
    self._identifier = self._get_privileges()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "nekrosis\core.py", line 126, in _get_privileges
    raise ValueError(f"Unexpected output from powershell:\n{results}")
ValueError: Unexpected output from powershell:
['']
[4816] Failed to execute script 'nekrosis_entry' due to unhandled exception!
```

When query SID manually, current user is not listed in `powershell.exe -Command Get-WMIObject win32_useraccount`

**Comment by khronokernel** [comment]
Further investigation, only affects VMware Fusion-based installation. Parallels installation correctly reports user's Security Identifier.

**Comment by khronokernel** [comment]
https://github.com/Nekrosis-ISS-Capstone/Nekrosis/commit/bc4a4ea06210bbf04b5ad61379bf1600d7261fd7
